###LOGIN
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
  "username": "test",
  "password": "Bluck@07"
}



###LOGOUT
POST http://127.0.0.1:8000/api/logout/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTA5ODQ3NCwiaWF0IjoxNzU1MDEyMDc0LCJqdGkiOiI2N2NmNWQyNjViZjM0YmVmOGE1YzZlZmMwZWJkMGFjNiIsInVzZXJfaWQiOiI3ZjhlZmRhNC01NThjLTQ3Y2EtOTMyMS0xOTZiZWRiNWIxMWYiLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20ifQ.mmXzYPIqM-ece3mBWGtl_GFpEyYweObcEX83iRthe40"
}

###FETSH USERS INFO
POST http://127.0.0.1:8000/api/logout/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc1NTA5ODQ3NCwiaWF0IjoxNzU1MDEyMDc0LCJqdGkiOiI2N2NmNWQyNjViZjM0YmVmOGE1YzZlZmMwZWJkMGFjNiIsInVzZXJfaWQiOiI3ZjhlZmRhNC01NThjLTQ3Y2EtOTMyMS0xOTZiZWRiNWIxMWYiLCJ1c2VybmFtZSI6InRlc3QiLCJlbWFpbCI6InRlc3RAdGVzdC5jb20ifQ.mmXzYPIqM-ece3mBWGtl_GFpEyYweObcEX83iRthe40"
}