# Generated by Django 5.0.3 on 2025-08-22 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(blank=True, help_text='Desktop, Laptop, Server, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='ip_addresses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='device',
            name='mac_addresses',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='device',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='processor',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='ram_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='device',
            name='storage_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='antivirus_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='auto_detected',
            field=models.BooleanField(default=False, help_text='Was this server auto-detected'),
        ),
        migrations.AddField(
            model_name='server',
            name='available_storage_gb',
            field=models.FloatField(blank=True, help_text='Available storage in GB', null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='cpu_info',
            field=models.TextField(blank=True, help_text='CPU details'),
        ),
        migrations.AddField(
            model_name='server',
            name='current_user',
            field=models.CharField(blank=True, help_text='Current Windows user', max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='default_gateway',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='detection_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='server',
            name='dns_servers',
            field=models.JSONField(blank=True, default=list, help_text='List of DNS servers'),
        ),
        migrations.AddField(
            model_name='server',
            name='domain',
            field=models.CharField(blank=True, help_text='Windows domain if applicable', max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='firewall_status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='hostname',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='Primary IP address', null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='is_admin_user',
            field=models.BooleanField(default=False, help_text='Is current user admin'),
        ),
        migrations.AddField(
            model_name='server',
            name='last_boot_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='last_info_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='server',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Primary MAC address', max_length=17),
        ),
        migrations.AddField(
            model_name='server',
            name='network_interfaces',
            field=models.JSONField(blank=True, default=list, help_text='List of network interfaces'),
        ),
        migrations.AddField(
            model_name='server',
            name='os_architecture',
            field=models.CharField(blank=True, help_text='e.g., x64, x86', max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='os_build',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='server',
            name='os_name',
            field=models.CharField(blank=True, help_text='e.g., Windows 11, Ubuntu 22.04', max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='os_version',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='server_name',
            field=models.CharField(blank=True, help_text='Computer/Server name', max_length=255),
        ),
        migrations.AddField(
            model_name='server',
            name='total_ram_gb',
            field=models.FloatField(blank=True, help_text='Total RAM in GB', null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='uptime_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='user_profile_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='server',
            name='workgroup',
            field=models.CharField(blank=True, help_text='Windows workgroup if applicable', max_length=255),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['hostname'], name='api_server_hostnam_1f2655_idx'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['ip_address'], name='api_server_ip_addr_97d6e1_idx'),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['mac_address'], name='api_server_mac_add_44772d_idx'),
        ),
    ]
