# Generated by Django 5.2.5 on 2025-08-24 12:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_server_owner_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.UUIDField(blank=True, help_text='ID of the user or admin who made the change.', null=True)),
                ('source_device_id', models.UUIDField(blank=True, help_text='ID of the device the change originated from.', null=True)),
                ('version', models.IntegerField(default=1)),
                ('group_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.licensekey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='api.group'),
        ),
    ]
