# Generated by Django 5.2.5 on 2025-08-12 22:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='is_key_active',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='licence_key',
        ),
        migrations.CreateModel(
            name='LicenseKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(help_text='The actual license key string.', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=False, help_text='True if this key has been assigned to an admin.')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assigned_admin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_license', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='admin',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='api.licensekey'),
        ),
        migrations.AddField(
            model_name='user',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='api.licensekey'),
        ),
    ]
