# Generated by Django 5.2.5 on 2025-08-14 21:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_admin_is_key_active_remove_admin_licence_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={},
        ),
        migrations.RenameField(
            model_name='device',
            old_name='server_id',
            new_name='server',
        ),
        migrations.AddField(
            model_name='admin',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='last_modified_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='parent_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='source_device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admin',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dataintegritylog',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dataintegritylog',
            name='last_modified_by',
            field=models.UUIDField(blank=True, help_text='ID of the user or admin who made the change.', null=True),
        ),
        migrations.AddField(
            model_name='dataintegritylog',
            name='source_device_id',
            field=models.UUIDField(blank=True, help_text='ID of the device the change originated from.', null=True),
        ),
        migrations.AddField(
            model_name='dataintegritylog',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='device',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_modified_by',
            field=models.UUIDField(blank=True, help_text='ID of the user or admin who made the change.', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='source_device_id',
            field=models.UUIDField(blank=True, help_text='ID of the device the change originated from.', null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='policy',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='last_modified_by',
            field=models.UUIDField(blank=True, help_text='ID of the user or admin who made the change.', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='source_device_id',
            field=models.UUIDField(blank=True, help_text='ID of the device the change originated from.', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='server',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='server',
            name='last_modified_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='source_device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='threat',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='last_modified_by',
            field=models.UUIDField(blank=True, help_text='ID of the user or admin who made the change.', null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='source_device_id',
            field=models.UUIDField(blank=True, help_text='ID of the device the change originated from.', null=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_modified_by',
            field=models.UUIDField(blank=True, help_text='ID of the user or admin who made the change.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='parent_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='source_device_id',
            field=models.UUIDField(blank=True, help_text='ID of the device the change originated from.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userphoto',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userphoto',
            name='last_modified_by',
            field=models.UUIDField(blank=True, help_text='ID of the user or admin who made the change.', null=True),
        ),
        migrations.AddField(
            model_name='userphoto',
            name='source_device_id',
            field=models.UUIDField(blank=True, help_text='ID of the device the change originated from.', null=True),
        ),
        migrations.AddField(
            model_name='userphoto',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='device',
            name='current_logged_in_user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='licensekey',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_data', models.JSONField(help_text='The raw JSON of the sync request from the client.')),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
