# Generated by Django 5.0.3 on 2025-08-08 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dvice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dvice',
        ),
    ]
