# Generated by Django 5.2.5 on 2025-08-26 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_group_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='parent_admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
