# Generated by Django 5.0.7 on 2025-10-09 10:51

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policy',
            old_name='policy_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='applicable_layer',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='created_by_admin_id',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='policy_json',
        ),
        migrations.AddField(
            model_name='policy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='owner_admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='policies_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='policy',
            name='parent_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_by', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('rule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('APP', 'Application Control (Executable/Hash)'), ('PORT', 'Network Port Control'), ('USB', 'USB Device Control'), ('FILE', 'File System Access'), ('URL', 'URL Filtering'), ('REG', 'Windows Registry Control'), ('INJECT', 'Process Injection Prevention')], help_text='The predefined type of the security rule.', max_length=10)),
                ('details', models.JSONField(default=dict, help_text='Specific parameters for the rule (e.g., port number, action, file path).')),
                ('is_active', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.policy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PolicyTarget',
            fields=[
                ('target_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_assignments_device', to='api.device')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_assignments_group', to='api.group')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='api.policy')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_assignments_user', to='api.user')),
            ],
            options={
                'unique_together': {('policy', 'device'), ('policy', 'group'), ('policy', 'user')},
            },
        ),
    ]
