# Generated by Django 5.2.5 on 2025-09-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_group_parent_admin_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dataintegritylog',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='system_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='threat',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userphoto',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admin',
            name='last_modified_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='source_device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataintegritylog',
            name='last_modified_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataintegritylog',
            name='source_device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_modified_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='source_device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='last_modified_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='source_device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='last_modified_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='policy',
            name='source_device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='auto_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='available_storage_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='cpu_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='current_user',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='dns_servers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='server',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_admin_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='last_modified_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='server',
            name='network_interfaces',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_architecture',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='server_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='server',
            name='source_device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='total_ram_gb',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='workgroup',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='threat',
            name='last_modified_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='threat',
            name='source_device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_modified_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='source_device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='last_modified_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='source_device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='server',
            index=models.Index(fields=['system_uuid'], name='api_server_system__2cf208_idx'),
        ),
    ]
