# Generated by Django 5.0.7 on 2025-09-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_admin_groups_admin_user_permissions_server_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='last_modified_by',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='source_device_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='licensekey',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
