# Generated by Django 5.0.7 on 2025-09-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_licensekey_is_deleted_licensekey_last_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='source_UUID',
            field=models.UUIDField(blank=True, help_text='The server_id of the LSC that sent this log.', null=True),
        ),
    ]
