# Generated by Django 5.0.7 on 2025-09-24 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_synclog_source_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synclog',
            name='source_UUID',
        ),
    ]
