# Generated by Django 5.0.7 on 2025-10-08 09:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_admin_last_modified_alter_admin_server_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='applicable_layer',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='created_by_admin_id',
        ),
        migrations.RemoveField(
            model_name='policy',
            name='policy_json',
        ),
        migrations.AddField(
            model_name='policy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='policy_version',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PolicyAssignment',
            fields=[
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_by', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('assignment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.policy')),
                ('target_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.device')),
                ('target_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.group')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified_by', models.UUIDField(blank=True, null=True)),
                ('source_device_id', models.UUIDField(blank=True, null=True)),
                ('version', models.IntegerField(default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('parent_id', models.UUIDField(blank=True, null=True)),
                ('rule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('APP', 'Application Control (Executable/Hash)'), ('PORT', 'Network Port Control'), ('USB', 'USB Device Control'), ('FILE', 'File System Access'), ('URL', 'URL Filtering'), ('REG', 'Windows Registry Control'), ('INJECT', 'Process Injection Prevention')], help_text='The type/template of the rule.', max_length=10)),
                ('actions', models.JSONField(default=list, help_text="List of actions to take, e.g., ['BLOCK', 'LOG']")),
                ('target_data', models.JSONField(help_text='Specific data for the rule target conforming to the rule_type schema.')),
                ('priority', models.IntegerField(default=1000, help_text='Lower number means higher priority.')),
                ('is_enabled', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=512, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.policy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='policyassignment',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('target_device__isnull', False), ('target_group__isnull', True)), models.Q(('target_device__isnull', True), ('target_group__isnull', False)), _connector='OR'), name='must_target_group_or_device'),
        ),
    ]
