# Generated by Django 5.0.7 on 2025-10-08 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_policy_applicable_layer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='parent_admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
