# Generated by Django 5.0.7 on 2025-10-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_policy_parent_admin_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='created_by',
        ),
    ]
