name: resilient_sync_app
description: "A Flutter application implementing the Resilient Chain of Command sync logic."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Local Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2

  # Networking
  dio: ^5.4.1
  connectivity_plus: ^5.0.2

  # Local Server
  shelf: ^1.4.1
  shelf_router: ^1.1.4

  # Configuration & Utils
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  json_annotation: ^4.8.1
  crypto: ^3.0.3
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  # Code Generators
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  async: ^2.11.0
